baseURL = "https://friendly-dijkstra-d7e7cf.netlify.com/"
languageCode = "en-us"
title = "Git Functional"
theme = "reveal-presentation"
[params]
description = "Description of presentation"
author = "Amos Garner"